Repository woowa-techcamp-2021/store-9, pull requests merged in 2021-08, with the labels that each got.

#16 frontend 환경 설정
  client/.eslintrc
  client/config/webpack.config.common.js
  client/config/webpack.config.dev.js
  client/config/webpack.config.prod.js
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  prettier.config.js
Labels: frontend, architecture

#17 라우터 구현
  client/package-lock.json
  client/src/Router.tsx
  client/src/app.tsx
  client/src/index.html
  client/src/index.tsx
Labels: frontend, architecture

#18 footer UI 구현
  client/config/webpack.config.common.js
  client/package-lock.json
  client/package.json
  client/src/app.tsx
  client/src/components/base/Footer/Footer.tsx
  client/src/static/assets/img/footer_logo.png
Labels: frontend

#19 헤더 구현
  client/config/webpack.config.common.js
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/app.tsx
  client/src/components/base/Header.tsx
  client/src/index.tsx
  client/src/static/assets/img/logo.png
  client/src/static/assets/img/search.png
  client/src/static/constants/index.ts
  client/src/static/style/init.css
Labels: frontend

#26 Mini CSS Extract Plugin 적용
  client/config/webpack.config.common.js
  client/package-lock.json
  client/package.json
  client/src/app.tsx
  client/src/static/style/init.css
Labels: frontend

#28 글로벌 스타일 구현
  client/src/app.tsx
  client/src/components/base/Footer/Footer.tsx
  client/src/index.html
  client/src/static/assets/img/baemin-favicon.png
  client/src/static/style/common.ts
  client/src/static/style/init.css
Labels: frontend

#31 커스텀 훅 useLocalStorage 구현
  client/src/customHooks/useLocalStorage.ts
Labels: frontend

#34 메인페이지 UI 구현
  client/src/app.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/Main/FeatureSection/FeatureSection.tsx
  client/src/components/Main/GiftSection/GiftSection.tsx
  client/src/components/base/Footer/Footer.tsx
  client/src/components/base/ItemLists/ItemLists.tsx
  client/src/index.html
  client/src/pages/Main/Main.tsx
  client/src/static/assets/img/baeminFavicon.png
  client/src/static/assets/img/bannerImage1.gif
  client/src/static/assets/img/bannerImage2.gif
  client/src/static/assets/img/bannerImage3.gif
  client/src/static/assets/img/footerLogo.png
  client/src/static/assets/img/giftSection1.png
  client/src/static/assets/img/giftSection2.png
  client/src/static/assets/img/sampleItem.jpeg
  client/src/static/style/common.ts
  client/src/static/style/init.css
Labels: frontend

#37 useInput 커스텀 훅 구현
  client/package-lock.json
  client/src/hooks/customHooks/useInput.ts
  client/src/hooks/customHooks/useLocalStorage.ts
  client/tsconfig.json
Labels: enhancement, frontend

#40 아이템 컴포넌트 UI 구현
  client/src/components/base/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/base/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/base/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/components/base/ItemLists/ItemLists.tsx
  client/src/components/base/ItemLists/ItemWishButton/ItemWishButton.tsx
  client/src/index.html
  client/src/static/assets/img/soldout.png
  client/src/static/style/common.ts
Labels: frontend

#35 장바구니 페이지 구현
  client/src/Router.tsx
  client/src/app.tsx
  client/src/components/base/BreadCrumbs/index.tsx
  client/src/components/base/Header.tsx
  client/src/components/base/ListTable/index.tsx
  client/src/components/base/PricePannel/index.tsx
  client/src/components/base/TableItem/index.tsx
  client/src/components/cart/CartContent.tsx
  client/src/components/cart/CartHeader.tsx
  client/src/components/cart/index.tsx
  client/src/hooks/context.tsx
  client/src/pages/cart/index.tsx
  client/src/static/assets/img/right_arrow.svg
  client/src/static/assets/img/right_arrow_grey.svg
  client/src/static/style/common.ts
Labels: frontend

#39 장바구니 테이블
  server/app.ts
  server/package-lock.json
  server/package.json
  server/src/entities/category.ts
  server/src/entities/discount.ts
  server/src/entities/like.ts
  server/src/entities/order-item.ts
  server/src/entities/order.ts
  server/src/entities/product-detail.ts
  server/src/entities/product.ts
  server/src/entities/qna.ts
  server/src/entities/review.ts
  server/src/entities/sale.ts
  server/src/entities/user.ts
Labels: backend, architecture

#42 헤더 상단 링크 구현
  client/src/components/base/Header.tsx
Labels: frontend

#44 useHistory, useLocation 구현
  client/src/Router.tsx
  client/src/app.tsx
  client/src/components/base/BreadCrumbs/index.tsx
  client/src/global.d.ts
  client/src/hooks/context.ts
  client/src/hooks/customHooks/useHistory.ts
  client/src/hooks/customHooks/useLocation.ts
Labels: frontend

#43 상품리스트 페이지 UI 구현
  client/src/app.tsx
  client/src/components/base/ItemFilterBar/ItemFilterBar.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/static/style/common.ts
Labels: frontend

#45 Login page + Signup Method page 구현
  client/src/app.tsx
  client/src/components/base/Button/index.tsx
  client/src/components/base/Input/index.tsx
  client/src/index.html
  client/src/pages/Login/index.tsx
  client/src/pages/SignupMethod/index.tsx
  client/tsconfig.json
Labels: frontend

#48 🚑 폴더명 변경
  client/src/pages/Main/index.tsx
Labels: bug, frontend, deploy

#49 Update README.md
  README.md
Labels: docs

#51 Arrow Button 구현 및 폰트 수정
  .github/auto_assign.yml
  client/src/app.tsx
  client/src/components/Main/FeatureSection/FeatureSection.tsx
  client/src/components/Main/GiftSection/GiftSection.tsx
  client/src/components/base/ButtonToMoveToTop/index.tsx
  client/src/components/base/Footer/Footer.tsx
  client/src/components/base/Header/Header.tsx
  client/src/components/base/ItemFilterBar/ItemFilterBar.tsx
  client/src/components/base/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/base/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/base/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/index.html
  client/src/pages/ProductList/index.tsx
  client/src/static/style/common.ts
  client/src/static/style/init.css
Labels: frontend

#52 주문하기 구현
  client/@types/global/index.d.ts
  client/@types/images/index.d.ts
  client/config/webpack.config.common.js
  client/package-lock.json
  client/package.json
  client/src/app.tsx
  client/src/components/Cart/CartContent.tsx
  client/src/components/Cart/index.tsx
  client/src/components/Order/OrderForm.tsx
  client/src/components/Order/Stage1.tsx
  client/src/components/Order/Stage2.tsx
  client/src/components/Order/Stepper.tsx
  client/src/components/Order/index.tsx
  client/src/components/base/BreadCrumbs/index.tsx
  client/src/components/base/Footer/index.tsx
  client/src/components/base/Header/index.tsx
  client/src/components/base/Input/index.tsx
  client/src/components/base/InputLabel/index.tsx
  client/src/components/base/OrderStageHeader/index.tsx
  client/src/components/base/PricePannel/index.tsx
  client/src/global.d.ts
  client/src/hooks/customHooks/useValidate.ts
  client/src/pages/Cart/index.tsx
  client/src/pages/Order/index.tsx
  client/src/static/assets/svg/index.ts
  client/src/static/assets/svg/right_arrow.svg
  client/src/static/assets/svg/right_arrow_grey.svg
  client/tsconfig.json
Labels: frontend

#56 404 page 구현
  client/package-lock.json
  client/src/app.tsx
  client/src/pages/NotFound/index.tsx
  client/src/static/assets/img/notfound.gif
Labels: frontend

#57 dynamic import을 이용한 초기 로딩 향상
  client/src/app.tsx
Labels: frontend

#59 API 적용 전 상품리스트 기능 구현
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/Main/FeatureSection/FeatureSection.tsx
  client/src/components/base/ButtonToMoveToTop/index.tsx
  client/src/components/base/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/base/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/base/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/components/base/ItemLists/ItemLists.tsx
  client/src/components/base/Loading/index.tsx
  client/src/dummy/index.ts
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/static/assets/img/loading.gif
Labels: frontend

#61 지난 로그인페이지 관련 리뷰 반영
  client/src/components/base/Button/index.tsx
  client/src/index.html
  client/src/pages/Login/index.tsx
  client/src/pages/SignupMethod/index.tsx
Labels: frontend

#53 Styled Component 구현
  client/package-lock.json
  client/package.json
  client/src/core/styled/index.tsx
  client/src/core/styled/tag.ts
  client/src/core/styled/util.ts
Labels: frontend

#71 마이페이지 회원정보 구현
  client/src/Router.tsx
  client/src/app.tsx
  client/src/components/Cart/CartContent.tsx
  client/src/components/MyPage/LeftNav.tsx
  client/src/components/MyPage/LikeContent.tsx
  client/src/components/MyPage/OrderContent.tsx
  client/src/components/MyPage/index.tsx
  client/src/components/base/Cell/index.tsx
  client/src/components/base/DurationFilter/index.tsx
  client/src/components/base/Header/index.tsx
  client/src/components/base/Input/index.tsx
  client/src/components/base/ListTable/index.tsx
  client/src/components/base/TableItem/index.tsx
  client/src/core/styled/index.tsx
  client/src/core/styled/util.ts
  client/src/hooks/customHooks/useInput.ts
  client/src/pages/MyPage/Like.tsx
  client/src/pages/MyPage/Order.tsx
  client/src/pages/MyPage/index.tsx
  client/src/static/assets/svg/clipboard_list.svg
  client/src/static/assets/svg/heart_solid.svg
  client/src/static/assets/svg/index.ts
  client/src/static/assets/svg/pen_solid.svg
  client/src/static/assets/svg/question_solid.svg
  client/src/static/assets/svg/shopping_cart.svg
  client/src/static/style/init.css
  client/src/utils/dateParse.ts
  client/tsconfig.json
Labels: frontend

#72 상품상세페이지 구현
  client/package-lock.json
  client/src/app.tsx
  client/src/components/DetailProduct/BuyButton/index.tsx
  client/src/components/DetailProduct/CartButton/index.tsx
  client/src/components/DetailProduct/Detail/index.tsx
  client/src/components/DetailProduct/DetailInfo/index.tsx
  client/src/components/DetailProduct/DetailInfoRecommend/index.tsx
  client/src/components/DetailProduct/DetailInfoTable/index.tsx
  client/src/components/DetailProduct/DetailTab/index.tsx
  client/src/components/DetailProduct/LikeButton/index.tsx
  client/src/components/DetailProduct/OverViewContent/index.tsx
  client/src/components/DetailProduct/Overview/index.tsx
  client/src/components/DetailProduct/ReplaceItemInfo/index.tsx
  client/src/components/DetailProduct/ShipInfo/index.tsx
  client/src/components/DetailProduct/StockSelector/index.tsx
  client/src/components/DetailProduct/TotalPrice/index.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/base/BoardHeader/index.tsx
  client/src/components/base/BoardPageNumber/index.tsx
  client/src/components/base/BoardPost/index.tsx
  client/src/components/base/Button/index.tsx
  client/src/components/base/ButtonToMoveToTop/index.tsx
  client/src/components/base/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/base/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/base/ItemLists/ItemLists.tsx
  client/src/components/base/PostModal/index.tsx
  client/src/components/base/ProductBoard/index.tsx
  client/src/index.html
  client/src/pages/DetailProduct/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/utils/calculateDiscount.ts
  client/src/utils/portal.ts
Labels: frontend

#73 Signup Page 구현
  client/package-lock.json
  client/package.json
  client/src/app.tsx
  client/src/components/base/Button/index.tsx
  client/src/components/base/Input/index.tsx
  client/src/hooks/customHooks/useAddress.ts
  client/src/hooks/customHooks/useInput.ts
  client/src/pages/Signup/index.tsx
  package-lock.json
Labels: frontend

#76 상품상세페이지 후기 별점기능 / 메인페이지 찜&평점 수 UI
  client/src/components/DetailProduct/DetailTab/index.tsx
  client/src/components/base/BoardPost/index.tsx
  client/src/components/base/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/base/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/base/ItemLists/ItemLists.tsx
  client/src/components/base/ItemLists/ItemWishButton/ItemWishButton.tsx
  client/src/components/base/PostModal/index.tsx
  client/src/components/base/Star/index.tsx
Labels: frontend

#90 주문하기, 장바구니 세부 기능 구현
  client/package-lock.json
  client/src/components/Cart/OptionModal.tsx
  client/src/components/Cart/index.tsx
  client/src/components/MyPage/QnAContent.tsx
  client/src/components/MyPage/Review.tsx
  client/src/components/Order/OrderForm.tsx
  client/src/components/Order/Stepper.tsx
  client/src/components/base/BreadCrumbs/index.tsx
  client/src/components/base/ListTable/index.tsx
  client/src/components/base/ModalWrapper/index.tsx
  client/src/components/base/PostModal/index.tsx
  client/src/components/base/PricePannel/index.tsx
  client/src/components/base/ProductBoard/index.tsx
  client/src/components/base/TableItem/index.tsx
  client/src/pages/Cart/index.tsx
  client/src/pages/MyPage/QnA.tsx
  client/src/pages/MyPage/Reivew.tsx
Labels: frontend

#82 FE 버그 및 자잘한 전체적 UI 추가 수정
  client/src/components/DetailProduct/Overview/index.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/ProductList/ItemFilterBar/index.tsx
  client/src/components/common/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/common/ItemLists/ItemLists.tsx
  client/src/pages/DetailProduct/index.tsx
  client/src/pages/Main/index.tsx
  client/src/static/style/init.css
Labels: frontend

#98 인풋 유효성 검사
  client/src/components/Order/OrderForm.tsx
  client/src/components/Order/Stage1.tsx
  client/src/components/Order/Stage2.tsx
  client/src/components/common/Input/index.tsx
  client/src/hooks/customHooks/useInput.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Signup/index.tsx
  client/src/utils/validation.tsx
Labels: frontend

#101 스마트레이어 구현
  client/src/components/Header/Navigation/index.tsx
  client/src/components/Header/SearchBar/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/Main/GiftSection/GiftSection.tsx
  client/src/static/assets/img/circle.png
  client/src/static/constants/index.ts
Labels: frontend

#89 Product, Category, Order, QnA > API
  client/src/apis/AuthApi.ts
  client/src/apis/BaseApi.ts
  client/src/apis/OrderApi.ts
  client/src/apis/ProductApi.ts
  client/src/utils/dateParse.ts
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/src/@types/express/index.d.ts
  server/src/controllers/CategoryController.ts
  server/src/controllers/OrderController.ts
  server/src/controllers/ProductController.ts
  server/src/controllers/QnAController.ts
  server/src/entities/discount.ts
  server/src/entities/order.ts
  server/src/entities/product.ts
  server/src/entities/qna.ts
  server/src/migrations/1629178613848-category-init.ts
  server/src/migrations/seeds/orderItemSeed.ts
  server/src/migrations/seeds/orderSeed.ts
  server/src/migrations/seeds/product.seed.ts
  server/src/migrations/seeds/user.seed.ts
  server/src/repositories/CategoryRepository.ts
  server/src/repositories/OrderRepository.ts
  server/src/repositories/ProductRepository.ts
  server/src/repositories/QnARepository.ts
  server/src/repositories/constants/product.ts
  server/src/routes/OrderRouter.ts
  server/src/routes/ProductRouter.ts
  server/src/routes/QnARouter.ts
  server/src/routes/index.ts
  server/tsconfig.json
  shared/dtos/auth/request.ts
  shared/dtos/base/response.ts
  shared/dtos/category/schema.ts
  shared/dtos/order-item/schema.ts
  shared/dtos/order/request.ts
  shared/dtos/order/response.ts
  shared/dtos/order/schema.ts
  shared/dtos/product/request.ts
  shared/dtos/product/response.ts
  shared/dtos/product/schema.ts
  shared/dtos/qna/request.ts
  shared/dtos/qna/response.ts
  shared/dtos/qna/schema.ts
  shared/dtos/review/schema.ts
  shared/dtos/user/schema.ts
Labels: backend, api

#107 🐛 마이페이지 useInput form 버그 수정
  client/src/components/common/DurationFilter/index.tsx
  client/src/pages/MyPage/Order.tsx
  client/src/pages/MyPage/QnA.tsx
Labels: bug, frontend

#104 Review API 구현
  .gitignore
  client/src/pages/Signup/index.tsx
  server/app.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/ReviewController.ts
  server/src/entities/review.ts
  server/src/middlewares/file.ts
  server/src/middlewares/review.ts
  server/src/repositories/review_repository.ts
  server/src/routes/AuthRouter.ts
  server/src/routes/ReviewRouter.ts
  server/src/routes/index.ts
  server/src/utils/constant.ts
  server/src/utils/review.ts
Labels: backend, api

#109 전체적인 UI 수정 작업
  client/package-lock.json
  client/src/components/Footer/index.tsx
  client/src/components/Header/Navigation/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/MyPage/LeftNav.tsx
  client/src/components/Order/Stage1.tsx
  client/src/components/Order/Stage2.tsx
  client/src/components/common/Cell/index.tsx
  client/src/components/common/DurationFilter/index.tsx
  client/src/components/common/ListTable/index.tsx
  client/src/components/common/PricePannel/index.tsx
  client/src/components/common/TableItem/index.tsx
  client/src/pages/Cart/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/Order/index.tsx
Labels: frontend

#83 라우터 파라미터 기능
  client/src/app.tsx
  client/src/core/Router.tsx
  client/src/static/constants/index.ts
Labels: frontend

#112 구매후기 api 연동
  client/package-lock.json
  client/package.json
  client/src/apis/BaseApi.ts
  client/src/apis/ReviewApi.ts
  client/src/components/MyPage/Review.tsx
  client/src/components/common/ListTable/index.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/hooks/customHooks/useInput.ts
  client/src/pages/MyPage/Reivew.tsx
  client/src/stores/RefreshStore.ts
  server/ormconfig.ts
  server/package-lock.json
  server/src/controllers/ReviewController.ts
  server/src/entities/review.ts
  server/src/repositories/review_repository.ts
  shared/dtos/review/request.ts
  shared/dtos/review/schema.ts
Labels: frontend, backend, api

#120 API 데이터 타입 정의
  client/src/apis/OrderApi.ts
  client/src/apis/QnaApi.ts
  client/src/apis/ReviewApi.ts
  client/src/apis/UserApi.ts
  client/src/stores/GlobalStore.ts
  server/src/entities/category.ts
  server/src/entities/order.ts
  shared/dtos/category/response.ts
  shared/dtos/order/request.ts
  shared/dtos/order/response.ts
  shared/dtos/order/schema.ts
  shared/dtos/product/response.ts
  shared/dtos/qna/request.ts
  shared/dtos/qna/response.ts
  shared/dtos/review/request.ts
  shared/dtos/review/response.ts
  shared/dtos/user/request.ts
  shared/dtos/user/response.ts
Labels: frontend, backend, api

#115 qna api 연동
  client/src/apis/QnaApi.ts
  client/src/apis/type/index.ts
  client/src/components/MyPage/QnAContent.tsx
  client/src/components/MyPage/Review.tsx
  client/src/components/common/DurationFilter/index.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/pages/MyPage/QnA.tsx
  client/src/stores/RefreshStore.ts
  server/src/controllers/QnAController.ts
  server/src/repositories/QnARepository.ts
Labels: frontend, backend, api

#118 구매내역 api 연동
  client/@types/images/index.d.ts
  client/src/apis/OrderApi.ts
  client/src/apis/ReviewApi.ts
  client/src/components/Header/index.tsx
  client/src/components/MyPage/OrderContent.tsx
  client/src/components/common/DurationFilter/index.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/pages/MyPage/Order.tsx
  server/src/controllers/OrderController.ts
  server/src/controllers/ReviewController.ts
  server/src/entities/review.ts
  server/src/repositories/OrderRepository.ts
  shared/dtos/order/request.ts
  shared/dtos/review/request.ts
Labels: frontend, backend, api

#119 리뷰 이미지 S3 업로드 및 수정, 삭제 미들웨어 구현
  server/app.ts
  server/package-lock.json
  server/package.json
  server/src/config/env.ts
  server/src/controllers/ReviewController.ts
  server/src/middlewares/auth.ts
  server/src/middlewares/file.ts
  server/src/middlewares/review.ts
  server/src/routes/ReviewRouter.ts
  server/src/utils/constant.ts
  server/src/utils/jwt.ts
  server/src/utils/review.ts
  server/src/utils/types/index.ts
Labels: backend

#168 메인페이지&카테고리 API연동 및 버그해결
  client/@types/global/index.d.ts
  client/src/apis/BaseApi.ts
  client/src/apis/ProductApi.ts
  client/src/app.tsx
  client/src/components/DetailProduct/OverViewContent/index.tsx
  client/src/components/DetailProduct/Overview/index.tsx
  client/src/components/DetailProduct/StockSelector/index.tsx
  client/src/components/DetailProduct/ZoomableImage/index.tsx
  client/src/components/Header/Navigation/index.tsx
  client/src/components/Header/SearchBar/index.tsx
  client/src/components/Header/ShortCuts/index.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/Main/FeatureSection/FeatureSection.tsx
  client/src/components/Main/GiftSection/GiftSection.tsx
  client/src/components/common/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/common/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/components/common/ItemLists/ItemLists.tsx
  client/src/dummy/index.ts
  client/src/pages/DetailProduct/index.tsx
  client/src/pages/Main/index.tsx
  client/src/remotes/ProductRemote.ts
  client/src/utils/calculateDiscount.ts
  server/src/controllers/ProductController.ts
  shared/dtos/product/response.ts
Labels: frontend

#169 주문하기 api 연동
  client/src/app.tsx
  client/src/components/Order/OrderForm.tsx
  client/src/components/Order/OrderSummary.tsx
  client/src/components/Order/Stage1.tsx
  client/src/components/Order/Stage2.tsx
  client/src/components/common/Input/index.tsx
  client/src/components/common/PricePannel/index.tsx
  client/src/hooks/context.ts
  client/src/hooks/customHooks/useInput.ts
  client/src/pages/Cart/index.tsx
  client/src/pages/FinishOrder/index.tsx
  client/src/pages/Order/index.tsx
  client/src/static/assets/img/orderFinish.png
  client/src/utils/validation.tsx
  client/src/utils/validatorMsg.ts
  server/src/controllers/OrderController.ts
  server/src/repositories/OrderRepository.ts
  shared/dtos/order/request.ts
Labels: frontend, api

#174 배포환경에서 origin 허용하도록 수정
  client/src/apis/BaseApi.ts
  server/app.ts
  server/config/env.js
  server/config/origins.js
  server/ormconfig.js
Labels: backend, deploy

#172 상품 리스트 페이지 API 연동
  client/package-lock.json
  client/src/apis/ProductApi.ts
  client/src/components/Header/Navigation/index.tsx
  client/src/components/ProductList/ItemFilterBar/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
  shared/dtos/product/request.ts
  shared/dtos/product/schema.ts
Labels: frontend

#175 이전 풀리퀘스트 버그 픽스
  client/src/pages/ProductList/index.tsx
  shared/dtos/product/request.ts
  shared/dtos/product/schema.ts
Labels: frontend

#177 WIP : 배포환경에서 테스트
  client/src/apis/UserApi.ts
  client/src/components/DetailProduct/Board/index.tsx
  client/src/components/DetailProduct/BoardPost/index.tsx
  client/src/components/DetailProduct/BuyButton/index.tsx
  client/src/components/DetailProduct/CartButton/index.tsx
  client/src/components/DetailProduct/LikeButton/index.tsx
  client/src/components/DetailProduct/OverViewContent/index.tsx
  client/src/components/DetailProduct/StockSelector/index.tsx
  client/src/components/common/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/pages/DetailProduct/index.tsx
  client/src/stores/DetailProductStore.ts
  server/src/controllers/OrderController.ts
Labels: frontend

#181 요청 Url, MobX 연결 관련 오류 수정
  client/src/apis/AuthApi.ts
  client/src/apis/BaseApi.ts
  client/src/app.tsx
  client/src/components/common/Callback/index.tsx
  server/src/controllers/AuthController.ts
Labels: bug

#180 Product Api 수정 및 개선
  client/package-lock.json
  client/package.json
  client/src/pages/ProductList/index.tsx
  server/app.ts
  server/src/controllers/ProductController.ts
  server/src/entities/product.ts
  server/src/repositories/ProductRepository.ts
  server/src/repositories/constants/product.ts
  server/src/utils/constant.ts
  server/src/utils/product.ts
  shared/dtos/product/response.ts
  shared/utils/translate.js
Labels: backend, api

#182 상세페이지 찜하기, 장바구니, 구매버튼, 리뷰 api 연동 테스트 결과
  client/src/components/DetailProduct/Board/index.tsx
  client/src/components/DetailProduct/BoardPost/index.tsx
  client/src/components/DetailProduct/BuyButton/index.tsx
  client/src/components/DetailProduct/CartButton/index.tsx
  client/src/components/DetailProduct/LikeButton/index.tsx
  client/src/components/DetailProduct/ZoomableImage/index.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/stores/AuthStore.ts
  client/src/stores/DetailProductStore.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/UserController.ts
  shared/dtos/order-item/schema.ts
Labels: frontend, api

#183 상품상세페이지에서 구매했는지 여부 알 수 있도록 isBuy 추가
  server/src/controllers/OrderController.ts
  server/src/controllers/ProductController.ts
  server/src/repositories/ProductRepository.ts
  server/src/utils/product.ts
  shared/dtos/product/response.ts
Labels: backend, api

#184 WIP : Feature/#171 업데이트 2차
  client/@types/global/index.d.ts
  client/src/components/DetailProduct/Board/index.tsx
  client/src/components/DetailProduct/BoardPageNumber/index.tsx
  client/src/components/DetailProduct/BoardPost/index.tsx
  client/src/components/DetailProduct/BuyButton/index.tsx
  client/src/components/DetailProduct/CartButton/index.tsx
  client/src/components/DetailProduct/DetailInfo/index.tsx
  client/src/components/DetailProduct/DetailInfoRecommend/index.tsx
  client/src/components/DetailProduct/DetailInfoTable/index.tsx
  client/src/components/DetailProduct/DetailTab/index.tsx
  client/src/components/DetailProduct/LikeButton/index.tsx
  client/src/components/DetailProduct/OverViewContent/index.tsx
  client/src/components/DetailProduct/Overview/index.tsx
  client/src/components/DetailProduct/StockSelector/index.tsx
  client/src/components/DetailProduct/TotalPrice/index.tsx
  client/src/components/Header/Navigation/index.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/Main/GiftSection/GiftSection.tsx
  client/src/components/common/ItemLists/ItemContent/ItemContent.tsx
  client/src/components/common/ItemLists/ItemImage/ItemImage.tsx
  client/src/components/common/ItemLists/ItemLabel/ItemLabel.tsx
  client/src/components/common/ItemLists/ItemLists.tsx
  client/src/hooks/context.ts
  client/src/pages/DetailProduct/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/stores/DetailProductStore.ts
  client/src/utils/errorMessage.ts
Labels: frontend

#185 protected route추가 + 깃허브 로그인 오류 수정(에러 핸들링) + mobx 액션 사용하도록 리팩토링
  client/src/apis/AuthApi.ts
  client/src/app.tsx
  client/src/components/Redirect/index.tsx
  client/src/components/common/Callback/index.tsx
  client/src/stores/AuthStore.ts
  client/src/utils/errorMessage.ts
  server/src/controllers/AuthController.ts
  server/src/utils/constant.ts
  shared/dtos/auth/request.ts
  shared/dtos/auth/response.ts
Labels: bug, enhancement

#186 WIP : Feature/#171 - 3차
  client/src/app.tsx
  client/src/components/DetailProduct/Board/index.tsx
  client/src/components/DetailProduct/BoardPost/index.tsx
  client/src/components/DetailProduct/LikeButton/index.tsx
  client/src/components/Header/Navigation/index.tsx
  client/src/components/Header/SearchBar/index.tsx
  client/src/components/common/ItemLists/ItemLists.tsx
  client/src/components/common/PostModal/index.tsx
  client/src/dummy/index.ts
  client/src/pages/ProductList/index.tsx
  client/src/static/constants/index.ts
  client/src/static/constants/words.ts
  client/src/static/crawlingDatas/b_store_008.json
  client/src/static/crawlingDatas/b_store_009.json
  client/src/static/crawlingDatas/b_store_011.json
  client/src/static/crawlingDatas/b_store_012.json
  client/src/static/crawlingDatas/b_store_014.json
  client/src/static/crawlingDatas/b_store_016.json
  client/src/static/crawlingDatas/b_store_017.json
  client/src/static/crawlingDatas/b_store_018.json
  client/src/static/crawlingDatas/b_store_019.json
  client/src/stores/CategoryStore.ts
  client/src/stores/HeaderStore.ts
Labels: frontend

#188 Fix bug
  client/src/components/Header/Navigation/index.tsx
Labels: frontend

#189 데이터 더 불러오는 버튼에 Spinner 추가
  client/src/pages/ProductList/index.tsx
Labels: frontend

#190 🚀 cicd
  .github/workflows/client-deploy.yml
  client/Dockerfile
  client/config/nginx.conf
Labels: deploy
